Add mode_num to too_manual
growth-astro/growth-too-marshal pull request #139
Opened 2020-11-11 17:32 UTC by ebellm

**Does this pull request make any changes to the database?**
No.

Addresses #138

2020-11-13 13:00 UTC, lpsinger commented
Instead of a "mode number" could we have textual descriptions of what the modes are?

2020-11-13 15:09 UTC, ebellm commented
I agree that would be a better user experience and less prone to error--unfortunately the complete set of mode numbers is not yet enumerated by the camera team, as the mode number encodes a complex set of configuration parameters that they plan to test on-sky.  I don't think we want to have to redeploy the marshal every time they tweak a parameter value in the readout electronics, so I suggest we stick with the box for now.

2020-11-13 15:12 UTC, lpsinger commented
> I don't think we want to have to redeploy the marshal every time they tweak a parameter value in the readout electronics

Why not? I think redeploying the marshal is entirely reasonable and expected when the values of the camera mode enumeration have changed.

2020-11-13 18:19 UTC, ebellm commented
The camera team can and I expect will deploy new modes during testing within the night--if we have to redeploy the marshal to reflect those changes it will severely hinder testing velocity.

2020-11-13 18:21 UTC, ebellm commented
(I'll add that the team is pushing to test on-sky tonight, so if we are able to get this through today it would be helpful.)

2020-11-13 18:21 UTC, lpsinger requested changes

2020-11-13 18:21 UTC, lpsinger commented on growth/too/templates/plan_manual.html
> +                <small id="balanceHelpBlock" class="form-text text-muted">
Mismatched indentation

2020-11-13 18:22 UTC, lpsinger commented
> The camera team can and I expect will deploy new modes during testing within the night--if we have to redeploy the marshal to reflect those changes it will severely hinder testing velocity.

In that case, how would we even know which mode number to request?

2020-11-13 18:55 UTC, ebellm commented
The scientist (@igorandreoni in this most immediate case) will be in close communication with the camera team during the testing period.

2020-11-14 18:28 UTC, lpsinger approved these changes

2020-11-14 18:30 UTC, lpsinger commented
The CI pipeline is failing and actually dumping core. I have never seen that before! But it's clearly unrelated to this PR, so I'll merge now. We'll need to fix the CI pipeline and the Docker Hub builds in order to deploy, though.

2020-11-14 18:30 UTC, merged